### ISSUE TITLE
Field to small

### ISSUE THREAD

**Issue by UserUserUser123** [heriet/redmine-selectbox-autocompleter#5]
Hey, 

If i create a new ticket, the field is big enough. 
If i edit a ticket, the field is only "60px". It's to arrow and should be 60 %. 
How can i change this? 
Or are there any bugfixes? 

Yours, 
Patrick

**Comment by heriet** [comment]
You can change it by custom css.

**Comment by UserUserUser123** [comment]
Do you mean the plugin stylesheet? I can't find the value "60px" in it.

**Comment by heriet** [comment]
You can custom css in several ways.

ex. use plugin like these.
http://www.redmine.org/plugins/redmine_view_customize
http://www.redmine.org/plugins/redmine_custom_css

or custom your redmine theme.

**Comment by UserUserUser123** [comment]
Edit: Have solved the problem with the !important - Command in CSS. 
Thank you
