### ISSUE TITLE
The set contents disappear after pressing the "Apply" button.

### ISSUE THREAD

**Issue by isap-hydn** [heriet/redmine-selectbox-autocompleter#7]
Thank you for a wonderful plugin.
But in the environment of bitnami-redmine 3.4.2-2stack
The set contents disappear after pressing the "Apply" button.

Perhaps my environment is bad.
I am pleased if you know something.

**Comment by heriet** [comment]
oh... I will check it

**Comment by heriet** [comment]
@isap-hydn Sorry for the late fix.
This issue fixed in #8 (version 1.1.2)
